import type { NextPage } from 'next'
import Head from 'next/head'
import GoalCards from '../components/goal-cards'
import InputGoalForm from '../components/input-goal-form'
import NavigationBar from '../components/navigation-bar'



const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Goalist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <InputGoalForm />
      <GoalCards />    
    </div>
  )
}

export default Home
